name: Build installers (macOS & Windows)

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: mac
            build_script: package:mac
            artifact_name: sticky-tasks-mac
          - os: windows-latest
            target: win
            build_script: package:win
            artifact_name: sticky-tasks-win
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Print versions (debug)
        run: |
          node -v
          npm -v
          npx electron --version || true
          npx electron-builder --version || true

      - name: Build installer
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
          ELECTRON_SKIP_BINARY_DOWNLOAD: "false"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ${{ matrix.build_script }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/*
